// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package kea

import (
	"context"
	"errors"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var (
	_ resource.Resource                = &dhcpv4SettingsResource{}
	_ resource.ResourceWithImportState = &dhcpv4SettingsResource{}
)

// dhcpv4SettingsID is the synthetic identifier for this singleton settings object.
const dhcpv4SettingsID = "kea-dhcpv4"

var dhcpv4SettingsReqOpts = opnsense.ReqOpts{
	GetEndpoint:         "/api/kea/dhcpv4/get",
	UpdateEndpoint:      "/api/kea/dhcpv4/set",
	ReconfigureEndpoint: "/api/kea/service/reconfigure",
	Monad:               "dhcpv4.general",
}

type dhcpv4SettingsResource struct{ client *opnsense.Client }

func newDHCPv4SettingsResource() resource.Resource { return &dhcpv4SettingsResource{} }

func (r *dhcpv4SettingsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_kea_dhcpv4_settings"
}

func (r *dhcpv4SettingsResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	r.client = client
}

func (r *dhcpv4SettingsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan DHCPv4SettingsResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := opnsense.UpdateSingleton(ctx, r.client, dhcpv4SettingsReqOpts, plan.toAPI(ctx)); err != nil {
		resp.Diagnostics.AddError("Error applying the Kea DHCPv4 general settings", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.GetSingleton[dhcpv4SettingsAPIResponse](ctx, r.client, dhcpv4SettingsReqOpts)
	if err != nil {
		resp.Diagnostics.AddError("Error reading the Kea DHCPv4 general settings after apply", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, dhcpv4SettingsID)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *dhcpv4SettingsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state DHCPv4SettingsResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	result, err := opnsense.GetSingleton[dhcpv4SettingsAPIResponse](ctx, r.client, dhcpv4SettingsReqOpts)
	if err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading the Kea DHCPv4 general settings", fmt.Sprintf("%s", err))
		return
	}
	state.fromAPI(ctx, result, dhcpv4SettingsID)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *dhcpv4SettingsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan DHCPv4SettingsResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := opnsense.UpdateSingleton(ctx, r.client, dhcpv4SettingsReqOpts, plan.toAPI(ctx)); err != nil {
		resp.Diagnostics.AddError("Error updating the Kea DHCPv4 general settings", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.GetSingleton[dhcpv4SettingsAPIResponse](ctx, r.client, dhcpv4SettingsReqOpts)
	if err != nil {
		resp.Diagnostics.AddError("Error reading the Kea DHCPv4 general settings after update", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, dhcpv4SettingsID)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// Delete is a no-op for the singleton; destroy only removes it from state.
func (r *dhcpv4SettingsResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
}

func (r *dhcpv4SettingsResource) ImportState(ctx context.Context, _ resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), types.StringValue(dhcpv4SettingsID))...)
}
